apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: syseleven-exporter
  description: Export quota and current usage from the SysEleven API as Prometheus metrics.
  annotations:
    github.com/project-slug: Staffbase/syseleven-exporter
  tags:
    - go
    - monitoring
    - infrastructure
spec:
  type: service
  lifecycle: production
